#!/bin/bash
#
# Moltbot Bootstrap Deployment Script
# Usage: ./deploy.sh [config.json]
#
# Installs Moltbot, applies config, and starts the gateway.
#

set -e

CONFIG_FILE="${1:-config.json}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

echo ""
echo "╔═══════════════════════════════════════════╗"
echo "║       Moltbot Bootstrap Deployment       ║"
echo "╚═══════════════════════════════════════════╝"
echo ""

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    error "Config file not found: $CONFIG_FILE"
fi

log "Using config: $CONFIG_FILE"

# Parse config values using jq (or Python fallback)
parse_json() {
    local key=$1
    if command -v jq &> /dev/null; then
        jq -r "$key // empty" "$CONFIG_FILE"
    else
        python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(eval('d$key') if eval('d$key') else '')" 2>/dev/null || echo ""
    fi
}

# Extract config values
WORKSPACE=$(parse_json '.workspace')
GATEWAY_PORT=$(parse_json '.gateway.port')
GATEWAY_TOKEN=$(parse_json '.gateway.token')
TELEGRAM_BOT_TOKEN=$(parse_json '.telegram.botToken')
ANTHROPIC_API_KEY=$(parse_json '.anthropic.apiKey')

# Defaults
WORKSPACE="${WORKSPACE:-/root/clawd}"
GATEWAY_PORT="${GATEWAY_PORT:-18181}"

echo ""
log "Configuration:"
echo "    Workspace:     $WORKSPACE"
echo "    Gateway Port:  $GATEWAY_PORT"
echo "    Telegram:      ${TELEGRAM_BOT_TOKEN:+configured}${TELEGRAM_BOT_TOKEN:-not set}"
echo "    Anthropic:     ${ANTHROPIC_API_KEY:+configured}${ANTHROPIC_API_KEY:-not set}"
echo ""

# Step 1: Check Node.js
echo "─────────────────────────────────────────────"
log "Step 1/5: Checking Node.js..."

if ! command -v node &> /dev/null; then
    warn "Node.js not found. Installing Node 22..."
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt-get install -y nodejs
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 22 ]; then
    error "Node.js 22+ required. Found: $(node -v)"
fi
log "Node.js $(node -v) ✓"

# Step 2: Install Moltbot
echo "─────────────────────────────────────────────"
log "Step 2/5: Installing Moltbot..."

if command -v clawdbot &> /dev/null; then
    CURRENT_VERSION=$(clawdbot --version 2>/dev/null || echo "unknown")
    log "Moltbot already installed: $CURRENT_VERSION"
    warn "Upgrading to latest..."
fi

curl -fsSL https://molt.bot/install.sh | bash -s -- --no-onboard --no-prompt
# Resolve binary name (may be clawdbot or moltbot)
MOLT_BIN=$(command -v moltbot 2>/dev/null || command -v clawdbot 2>/dev/null || echo "moltbot")
log "Moltbot $($MOLT_BIN --version) installed ✓"

# Step 3: Create workspace
echo "─────────────────────────────────────────────"
log "Step 3/5: Setting up workspace..."

mkdir -p "$WORKSPACE"
mkdir -p "$WORKSPACE/memory"
log "Workspace created: $WORKSPACE"

# Step 4: Set environment variables
echo "─────────────────────────────────────────────"
log "Step 4/5: Configuring environment..."

ENV_FILE="/etc/moltbot.env"

# Build env file
cat > "$ENV_FILE" << EOF
# Moltbot Environment Configuration
# Generated by deploy.sh on $(date)

CLAWDBOT_GATEWAY_PORT=$GATEWAY_PORT
EOF

if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> "$ENV_FILE"
    log "Anthropic API key configured"
fi

if [ -n "$GATEWAY_TOKEN" ]; then
    echo "CLAWDBOT_GATEWAY_TOKEN=$GATEWAY_TOKEN" >> "$ENV_FILE"
    log "Gateway auth token configured"
fi

chmod 600 "$ENV_FILE"
log "Environment file: $ENV_FILE"

# Step 5: Generate Moltbot config
echo "─────────────────────────────────────────────"
log "Step 5/5: Generating Moltbot config..."

MOLTBOT_CONFIG_DIR="$HOME/.clawdbot"
mkdir -p "$MOLTBOT_CONFIG_DIR"

cat > "$MOLTBOT_CONFIG_DIR/clawdbot.json" << EOF
{
  "agents": {
    "defaults": {
      "workspace": "$WORKSPACE",
      "maxConcurrent": 4,
      "subagents": {
        "maxConcurrent": 8
      },
      "compaction": {
        "mode": "safeguard"
      }
    }
  },
  "gateway": {
    "port": $GATEWAY_PORT,
    "mode": "local",
    "bind": "lan",
    "auth": {
      "mode": "token",
      "token": "${GATEWAY_TOKEN:-$(openssl rand -hex 32)}"
    }
  },
  "channels": {
    "telegram": {
      "enabled": ${TELEGRAM_BOT_TOKEN:+true}${TELEGRAM_BOT_TOKEN:-false},
      "botToken": "${TELEGRAM_BOT_TOKEN:-}",
      "dmPolicy": "pairing",
      "groupPolicy": "allowlist",
      "streamMode": "partial"
    }
  },
  "plugins": {
    "entries": {
      "telegram": {
        "enabled": ${TELEGRAM_BOT_TOKEN:+true}${TELEGRAM_BOT_TOKEN:-false}
      }
    }
  },
  "messages": {
    "ackReactionScope": "group-mentions"
  },
  "commands": {
    "native": "auto",
    "nativeSkills": "auto"
  }
}
EOF

log "Config written: $MOLTBOT_CONFIG_DIR/clawdbot.json"

# Create systemd service
echo "─────────────────────────────────────────────"
log "Creating systemd service..."

cat > /etc/systemd/system/moltbot-gateway.service << EOF
[Unit]
Description=Moltbot Gateway
After=network.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
ExecStart=/usr/bin/clawdbot gateway
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable moltbot-gateway
log "Systemd service created and enabled"

# Start the gateway
echo "─────────────────────────────────────────────"
log "Starting Moltbot Gateway..."

systemctl start moltbot-gateway
sleep 3

if systemctl is-active --quiet moltbot-gateway; then
    log "Gateway started successfully! ✓"
else
    warn "Gateway may have issues. Check: journalctl -u moltbot-gateway -f"
fi

echo ""
echo "╔═══════════════════════════════════════════╗"
echo "║          Deployment Complete! 🎉          ║"
echo "╚═══════════════════════════════════════════╝"
echo ""
echo "  Gateway:    http://localhost:$GATEWAY_PORT"
echo "  Workspace:  $WORKSPACE"
echo "  Config:     $MOLTBOT_CONFIG_DIR/clawdbot.json"
echo "  Logs:       journalctl -u moltbot-gateway -f"
echo ""

if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
    echo "  Telegram:   Enabled - DM your bot to pair!"
    echo ""
fi

echo "  Commands:"
echo "    clawdbot status          # Check status"
echo "    clawdbot pairing list    # List pending pairings"
echo "    systemctl restart moltbot-gateway"
echo ""
